[package]
name = "kimview"
version = "0.1.0"
edition = "2021"

[lib]
name = "kimview"
crate-type = ["staticlib"]

[profile.release]
opt-level = 3
lto = true

[dependencies]
libc = "0.2"
crossterm = "0.26.0"